spring:
 datasource:
    url: jdbc:mysql://voting-api-db.ctscyewa6ar2.us-east-2.rds.amazonaws.com:3306/voting_api_db?useTimezone=true&serverTimezone=UTC
    username: docker
    password: dockerpass123
    driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
 servlet:
   multipart:
     enabled: true
     file-size-threshold: 2KB
     max-file-size: 200MB
     max-request-size: 215MB

application:
    name: VotingAPI

server:
  servlet.context-path: /vote/v1
  port: 80